/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PublicacionesIndexRouteImport } from './routes/publicaciones.index'
import { Route as PublicacionesPublicacionIdRouteImport } from './routes/publicaciones.$publicacionId'
import { Route as UsuariosUsuarioIdRouteImport } from './routes/usuarios.$usuarioId'
import { Route as VendedoresTopRouteImport } from './routes/vendedores.top'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacionesIndexRoute = PublicacionesIndexRouteImport.update({
  id: '/publicaciones/',
  path: '/publicaciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacionesPublicacionIdRoute =
  PublicacionesPublicacionIdRouteImport.update({
    id: '/publicaciones/$publicacionId',
    path: '/publicaciones/$publicacionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const UsuariosUsuarioIdRoute = UsuariosUsuarioIdRouteImport.update({
  id: '/usuarios/$usuarioId',
  path: '/usuarios/$usuarioId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedoresTopRoute = VendedoresTopRouteImport.update({
  id: '/vendedores/top',
  path: '/vendedores/top',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/compras': typeof ComprasRoute
  '/login': typeof LoginRoute
  '/publicar': typeof PublicarRoute
  '/registro': typeof RegistroRoute
  '/publicaciones/$publicacionId': typeof PublicacionesPublicacionIdRoute
  '/usuarios/$usuarioId': typeof UsuariosUsuarioIdRoute
  '/vendedores/top': typeof VendedoresTopRoute
  '/publicaciones/': typeof PublicacionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/compras': typeof ComprasRoute
  '/login': typeof LoginRoute
  '/publicar': typeof PublicarRoute
  '/registro': typeof RegistroRoute
  '/publicaciones/$publicacionId': typeof PublicacionesPublicacionIdRoute
  '/usuarios/$usuarioId': typeof UsuariosUsuarioIdRoute
  '/vendedores/top': typeof VendedoresTopRoute
  '/publicaciones': typeof PublicacionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/compras': typeof ComprasRoute
  '/login': typeof LoginRoute
  '/publicar': typeof PublicarRoute
  '/registro': typeof RegistroRoute
  '/publicaciones/$publicacionId': typeof PublicacionesPublicacionIdRoute
  '/usuarios/$usuarioId': typeof UsuariosUsuarioIdRoute
  '/vendedores/top': typeof VendedoresTopRoute
  '/publicaciones/': typeof PublicacionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categorias'
    | '/compras'
    | '/login'
    | '/publicar'
    | '/registro'
    | '/publicaciones/$publicacionId'
    | '/usuarios/$usuarioId'
    | '/vendedores/top'
    | '/publicaciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categorias'
    | '/compras'
    | '/login'
    | '/publicar'
    | '/registro'
    | '/publicaciones/$publicacionId'
    | '/usuarios/$usuarioId'
    | '/vendedores/top'
    | '/publicaciones'
  id:
    | '__root__'
    | '/'
    | '/categorias'
    | '/compras'
    | '/login'
    | '/publicar'
    | '/registro'
    | '/publicaciones/$publicacionId'
    | '/usuarios/$usuarioId'
    | '/vendedores/top'
    | '/publicaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriasRoute: typeof CategoriasRoute
  ComprasRoute: typeof ComprasRoute
  LoginRoute: typeof LoginRoute
  PublicarRoute: typeof PublicarRoute
  RegistroRoute: typeof RegistroRoute
  PublicacionesPublicacionIdRoute: typeof PublicacionesPublicacionIdRoute
  UsuariosUsuarioIdRoute: typeof UsuariosUsuarioIdRoute
  VendedoresTopRoute: typeof VendedoresTopRoute
  PublicacionesIndexRoute: typeof PublicacionesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicaciones/': {
      id: '/publicaciones/'
      path: '/publicaciones'
      fullPath: '/publicaciones/'
      preLoaderRoute: typeof PublicacionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicaciones/$publicacionId': {
      id: '/publicaciones/$publicacionId'
      path: '/publicaciones/$publicacionId'
      fullPath: '/publicaciones/$publicacionId'
      preLoaderRoute: typeof PublicacionesPublicacionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/$usuarioId': {
      id: '/usuarios/$usuarioId'
      path: '/usuarios/$usuarioId'
      fullPath: '/usuarios/$usuarioId'
      preLoaderRoute: typeof UsuariosUsuarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedores/top': {
      id: '/vendedores/top'
      path: '/vendedores/top'
      fullPath: '/vendedores/top'
      preLoaderRoute: typeof VendedoresTopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriasRoute: CategoriasRoute,
  ComprasRoute: ComprasRoute,
  LoginRoute: LoginRoute,
  PublicarRoute: PublicarRoute,
  RegistroRoute: RegistroRoute,
  PublicacionesPublicacionIdRoute: PublicacionesPublicacionIdRoute,
  UsuariosUsuarioIdRoute: UsuariosUsuarioIdRoute,
  VendedoresTopRoute: VendedoresTopRoute,
  PublicacionesIndexRoute: PublicacionesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
